remote_theme: "mmistakes/minimal-mistakes@4.16.3"
plugins:
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
minimal_mistakes_skin: "neon"
title: "Developer Note"
name: "Jaxon's Notebook"
logo: "/asset/logo/logo_jaxon_pornhub_style.png"
repository: "tianhaoz95/developer-note"
read_time: true
words_per_minute: 200
comments:
  provider: "disqus"
  disqus:
    shortname: "jaxon-chiaus-developer-note"
search: true
author:
  name     : "Jaxon Chiau"
  avatar   : "/asset/avatar/jaxon_chiau_22yo_at_yantai.png"
  bio      : "I like to code while drinking boba."
  location : "San Jose, CA, USA"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/tianhao-zhou-40244010a/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/tianhaoz95"
    - label: "Stack Overflow"
      icon: "fab fa-fw fa-stack-overflow"
      url: "https://stackoverflow.com/users/6750238/jaxon"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/TianhaozZhou"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/jaxonchiau95"
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/tianhao-zhou-40244010a/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/tianhaoz95"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/TianhaozZhou"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/jaxonchiau95"
timezone: America/Los_Angeles
future: true
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
exclude:
  - "projects"
paginate: 5
paginate_path: /page:num/
twitter:
  username: "TianhaozZhou"
facebook:
  app_id: 824229744625887
  username: "tianhaozhou95"
og_image: "/asset/logo/logo_pornhub_style.png"
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-121674883-3"
    anonymize_ip: false